---
apiVersion: v1
kind: Secret
metadata:
  name: weather-app-mysql-password
  namespace: simple-deploy
type: Opaque
data:
  mysql_password: bXktc2VjcmV0LXB3

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: simple-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ghazouanihm/weatherapp-auth:10.6
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "db-service"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: weather-app-mysql-password
                  key: mysql_password
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: simple-deploy
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
  - name: tcp-auth
    protocol: "TCP"
    port: 8080
    targetPort: 8080
