apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: simple-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mysql
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "my-secret-pw"
          ports:
            - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: simple-deploy
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
  - name: tcp-db
    protocol: "TCP"
    port: 3306
    targetPort: 3306
