apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: simple-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: ghazouanihm/weatherapp-ui:15.6
          imagePullPolicy: Always
          env:
            - name: AUTH_HOST
              value: "auth-service"
            - name: AUTH_PORT
              value: "8080"
            - name: WEATHER_HOST
              value: "weather-service"
            - name: WEATHER_PORT
              value: "5000"
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: simple-deploy
spec:
  selector:
    app: ui
  type: LoadBalancer
  ports:
  - name: tcp-ui
    protocol: "TCP"
    port: 3000
    targetPort: 3000