---
apiVersion: v1
kind: Secret
metadata:
  name: weather-app-api-key
  namespace: simple-deploy
type: Opaque
data:
  api_key: OWJmOGJhOTY1N2JhNDY3Y2E0YjEyMzU0MTIzMTEwNQ==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
  namespace: simple-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - name: weather
          image: ghazouanihm/weatherapp-weather:10.6
          imagePullPolicy: Always
          env:
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: weather-app-api-key
                  key: api_key
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: weather-service
  namespace: simple-deploy
spec:
  selector:
    app: weather
  type: ClusterIP
  ports:
  - name: tcp-weather
    protocol: "TCP"
    port: 5000
    targetPort: 5000