apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ghazouanihm/weatherapp-auth:1.0
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "db-service"
            - name: DB_PASSWORD
              value: "my-secret-pw"
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
