---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-ui:11.5
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp-ui:11.5
      version: v2
  template:
    metadata:
      labels:
        app: weatherapp-ui:11.5
        version: v2
        istio: monitor
    spec:
      containers:
        - image: ghazouanihm/weatherapp-ui:11.5
          imagePullPolicy: Always
          name: weatherapp-ui:11.5
          env:
            - name: AUTH_HOST
              value: "auth-service"
            - name: AUTH_PORT
              value: "8080"
            - name: WEATHER_HOST
              value: "weather-service"
            - name: WEATHER_PORT
              value: "5000"
          ports:
            - name: http
              containerPort: 3000