---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-v2
  namespace: istio-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
      version: v2
  template:
    metadata:
      labels:
        app: ui
        version: v2
        istio: monitor
    spec:
      containers:
        - image: ghazouanihm/weatherapp-ui:14.6
          imagePullPolicy: Always
          name: ui
          env:
            - name: AUTH_HOST
              value: "weatherapp-auth-istio-service"
            - name: AUTH_PORT
              value: "8080"
            - name: WEATHER_HOST
              value: "weatherapp-weather-istio-service"
            - name: WEATHER_PORT
              value: "5000"
          ports:
            - name: ui-tcp
              containerPort: 3000