apiVersion: v1
kind: Service
metadata:
  name: weatherapp-ui-rollout-service
  namespace: staging
spec:
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: weatherapp-ui-rollout