apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: weatherapp-ui-rollout
  namespace: rollout-deploy
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 30
      - pause: {duration: 20}
      - setWeight: 60
      - pause: {duration: 20}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: weatherapp-ui-rollout
  template:
    metadata:
      labels:
        app: weatherapp-ui-rollout
    spec:
      containers:
      - name: weatherapp-ui-rollout
        image: ghazouanihm/weatherapp-ui:1.0
        env:
            - name: AUTH_HOST
              value: "auth-service"
            - name: AUTH_PORT
              value: "8080"
            - name: WEATHER_HOST
              value: "weather-service"
            - name: WEATHER_PORT
              value: "5000"
        ports:
        - name: tcp-ui
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m

---

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: weatherapp-auth-rollout
  namespace: rollout-deploy
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 30
      - pause: {duration: 20}
      - setWeight: 60
      - pause: {duration: 20}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: weatherapp-auth-rollout
  template:
    metadata:
      labels:
        app: weatherapp-auth-rollout
    spec:
      containers:
      - name: weatherapp-auth-rollout
        image: ghazouanihm/weatherapp-auth:1.0
        env:
            - name: DB_HOST
              value: "db-service"
            - name: DB_PASSWORD
              value: "my-secret-pw"
        ports:
        - name: tcp-auth
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m

---

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: weatherapp-db-rollout
  namespace: rollout-deploy
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 30
      - pause: {duration: 20}
      - setWeight: 60
      - pause: {duration: 20}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: weatherapp-db-rollout
  template:
    metadata:
      labels:
        app: weatherapp-db-rollout
    spec:
      containers:
      - name: weatherapp-db-rollout
        image: ghazouanihm/weatherapp-db:1.0
        env:
            - name: MYSQL_ROOT_PASSWORD
              value: "my-secret-pw"
        ports:
        - name: tcp-db
          containerPort: 3306
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m

---

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: weatherapp-weather-rollout
  namespace: rollout-deploy
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 30
      - pause: {duration: 20}
      - setWeight: 60
      - pause: {duration: 20}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: weatherapp-weather-rollout
  template:
    metadata:
      labels:
        app: weatherapp-weather-rollout
    spec:
      containers:
      - name: weatherapp-weather-rollout
        image: ghazouanihm/weatherapp-weather:1.0
        env:
            - name: APIKEY
              value: "9bf8ba9657ba467ca4b123541231105"
        ports:
        - name: tcp-weather
          containerPort: 5000
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
