apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: weatherapp-ui-rollout
  namespace: staging
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 20}
      - setWeight: 40
      - pause: {duration: 20}
      - setWeight: 60
      - pause: {duration: 20}
      - setWeight: 80
      - pause: {duration: 20}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: weatherapp-ui-rollout
  template:
    metadata:
      labels:
        app: weatherapp-ui-rollout
    spec:
      containers:
      - name: weatherapp-ui-rollout
        image: ghazouanihm/weatherapp-ui:2.0
        env:
            - name: AUTH_HOST
              value: "auth-service"
            - name: AUTH_PORT
              value: "8080"
            - name: WEATHER_HOST
              value: "weather-service"
            - name: WEATHER_PORT
              value: "5000"
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m